name: Build BlackThunder OS for Redmi 10C

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up job
        run: echo "Starting BlackThunder OS build for Redmi 10C"

      - name: Setup dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y git curl repo bc bison build-essential \
            ccache flex g++-multilib gcc-multilib gnupg gperf libxml2-utils \
            make python3 python3-pip unzip zip zlib1g-dev libncurses5-dev \
            libncurses5-dev:i386 openjdk-11-jdk

      - name: Install repo tool
        run: |
          mkdir -p ~/bin
          curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
          chmod a+x ~/bin/repo
          echo 'export PATH=~/bin:$PATH' >> ~/.bashrc
          source ~/.bashrc

      - name: Initialize BlackThunder Source
        run: |
          mkdir -p ~/blackthunder
          cd ~/blackthunder
          repo init -u https://github.com/LineageOS/android.git -b lineage-20.0 --depth=1
          repo sync -c --no-tags --no-clone-bundle -j$(nproc)

      - name: Clone Device Tree for Redmi 10C
        run: |
          cd ~/blackthunder
          git clone https://github.com/Harish020904/device_xiaomi_fog.git device/xiaomi/fog
          # Add kernel & vendor clones here if needed

      - name: Setup build environment and compile
        run: |
          cd ~/blackthunder
          source build/envsetup.sh
          lunch lineage_fog-userdebug
          make bacon -j$(nproc)

      - name: Upload ROM as GitHub Artifact
        uses: actions/upload-artifact@v3
        with:
          name: BlackThunder-Redmi10C-ROM
          path: ~/blackthunder/out/target/product/fog/*.zip
